services:
  db:
    image: postgres:16.2
    environment:
      POSTGRES_DB: lottery_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - ./db-init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
